// NOTE : CE FICHIER NE DEVRAIT PAS SE RETROUVER SUR GITLAB PUISQU'IL CONTIENT DES DONNÉES SENSIBLES POUR LA CONNEXION À LA BASE DE DONNÉES
// TOUTEFOIS, POUR FACILITER LA CORRECTION DU SPRINT 3, NOUS L'AVONS TOUT DE MÊME INCLUS

export const DATABASE_URL = 'mongodb+srv://sysadmin:admin@scrabble.vzndp3k.mongodb.net/myFirstDatabase?retryWrites=true&w=majority';
export const DATABASE_NAME = 'Scrabble';
